# Neden NumPy?

## Bu bir alt başlıktır

In [ ]:
a = [1,2,3,4]
b = [2,3,4,5]
a

[1, 2, 3, 4]

In [10]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [7]:
a*b

array([ 2,  6, 12, 20])

In [19]:
np.array([1.2,1,2,3,4], dtype = "int")

array([1, 1, 2, 3, 4])

In [12]:
type(a)

numpy.ndarray

In [ ]:
#sifirdan array olusturma

In [21]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [26]:
np.arange(0,31,3) #(!!!)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [27]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [28]:
np.random.normal(10,4,(3,4)) #ortalama 10 ss 4 (!!!)

array([[ 5.17804583,  8.59790688, 12.86405545,  2.66370819],
       [ 5.46745398, 10.8027406 , 12.75894157, 10.02618218],
       [12.75005749,  9.12826659, 19.36705368,  8.19292896]])

In [29]:
np.random.randint(0,10,(3,3)) #(!!!)

array([[4, 1, 9],
       [5, 7, 3],
       [6, 6, 7]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [30]:
np.random.randint(10, size=10)

array([4, 5, 3, 0, 5, 2, 2, 3, 7, 9])

In [31]:
a = np.random.randint(10, size=10)

In [32]:
a.ndim

1

In [33]:
a.shape

(10,)

In [34]:
a.size

10

In [35]:
a.dtype

dtype('int64')

In [36]:
b = np.random.randint(10, size = (3,5))

In [37]:
b

array([[6, 5, 3, 2, 3],
       [7, 1, 8, 4, 7],
       [4, 7, 3, 4, 4]])

In [40]:
b.ndim

2

In [41]:
b.shape

(3, 5)

In [42]:
b.size

15

In [43]:
b.dtype

dtype('int64')

# Yeniden Şekillendirme (reshaping)

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
  a = np.arange(1,10)

In [49]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a.ndim

1

In [52]:
b = a.reshape((1,9))

In [54]:
b.ndim

2

In [55]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Array Birleştirme (Concantration)

In [56]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [58]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [59]:
z = np.array([7,8,9])

In [60]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
#iki boyut

In [63]:
a = np.array([[1,2,3],
             [4,5,6]])

In [64]:
np.concatenate([a,a]) #satır-sütuna çevirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [65]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [66]:
x = np.array([1,2,3,99,99,3,2,1])

In [67]:
np.split(x,[3,5]) #3te ve 5te ayır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [68]:
a,b,c = np.split(x,[3,5]) 

In [69]:
a

array([1, 2, 3])

In [70]:
b

array([99, 99])

In [71]:
c

array([3, 2, 1])

In [72]:
#iki boyutlu ayırma

In [73]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [75]:
ust, alt =np.vsplit(m, [2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [77]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
np.hsplit(m, [2]) # matris sütunu ayırma

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

# Array Sıralama (Sorting)

In [79]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [80]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [82]:
v.sort() #array yapısını değiştirir

In [83]:
v

array([1, 2, 3, 4, 5])

In [84]:
#iki boyutlu sıralama

In [87]:
m = np.random.normal(20,5,(3,3))
m

array([[27.07834191, 23.07367247, 12.20412459],
       [14.60574688, 22.06269391, 18.15116874],
       [20.09602152, 31.07069409, 24.88363485]])

In [88]:
np.sort(m, axis = 1) #satırları sıralama

array([[12.20412459, 23.07367247, 27.07834191],
       [14.60574688, 18.15116874, 22.06269391],
       [20.09602152, 24.88363485, 31.07069409]])

In [89]:
np.sort(m, axis = 0) #sütünları sıralama

array([[14.60574688, 22.06269391, 12.20412459],
       [20.09602152, 23.07367247, 18.15116874],
       [27.07834191, 31.07069409, 24.88363485]])

# Index ile Elemanlara Erişmek

In [91]:
a = np.random.randint(10, size = 10)
a

array([6, 5, 4, 7, 8, 7, 6, 5, 0, 1])

In [92]:
a[-1]

1

In [94]:
a[0] = 100
a

array([100,   5,   4,   7,   8,   7,   6,   5,   0,   1])

In [96]:
m = np.random.randint(10, size = (3,5))
m

array([[5, 2, 3, 8, 1],
       [9, 3, 9, 4, 2],
       [5, 0, 3, 5, 1]])

In [97]:
m[0,0]

5

In [98]:
m[1,4] = 99
m

array([[ 5,  2,  3,  8,  1],
       [ 9,  3,  9,  4, 99],
       [ 5,  0,  3,  5,  1]])

In [100]:
m[1,4] = 2.2
m

array([[5, 2, 3, 8, 1],
       [9, 3, 9, 4, 2],
       [5, 0, 3, 5, 1]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [102]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [103]:
a[0:3]

array([20, 21, 22])

In [104]:
a[1::2] #1den başlayıp 2şer gidiyor 

array([21, 23, 25, 27, 29])

In [105]:
#iki boyutlu slice işlemleri

In [106]:
m = np.random.randint(10, size = (5,5))
m

array([[2, 9, 2, 6, 9],
       [7, 4, 6, 8, 6],
       [3, 3, 9, 0, 5],
       [7, 5, 5, 3, 6],
       [1, 5, 1, 9, 6]])

In [110]:
m[:,0] #bütün satırlar 0.sütün

array([2, 7, 3, 7, 1])

In [108]:
m[:,4]

array([9, 6, 5, 6, 6])

In [109]:
m[0,:]

array([2, 9, 2, 6, 9])

In [112]:
m[0]

array([2, 9, 2, 6, 9])

In [111]:
m[1,:]

array([7, 4, 6, 8, 6])

In [113]:
m[1]

array([7, 4, 6, 8, 6])

In [114]:
m[0:2,0:3]

array([[2, 9, 2],
       [7, 4, 6]])

# Alt Küme Üzerinde İşlem Yapmak (asıl arrayı etkilemeden)

In [116]:
a= np.random.randint(10, size = (5,5))
a

array([[9, 0, 5, 6, 6],
       [9, 4, 4, 9, 8],
       [2, 5, 6, 0, 7],
       [3, 0, 4, 7, 4],
       [4, 0, 0, 4, 1]])

In [117]:
alt_a = a[0:3, 0:2]
alt_a

array([[9, 0],
       [9, 4],
       [2, 5]])

In [119]:
alt_a[0,0] = 9999
alt_a[1,1] = 888
alt_a

array([[9999,    0],
       [   9,  888],
       [   2,    5]])

In [120]:
a

array([[9999,    0,    5,    6,    6],
       [   9,  888,    4,    9,    8],
       [   2,    5,    6,    0,    7],
       [   3,    0,    4,    7,    4],
       [   4,    0,    0,    4,    1]])

In [121]:
m = np.random.randint(10, size = (5,5))
m

array([[6, 6, 8, 4, 7],
       [5, 6, 3, 5, 1],
       [3, 2, 0, 9, 6],
       [5, 4, 6, 0, 5],
       [8, 7, 8, 0, 8]])

In [123]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[6, 6],
       [5, 6],
       [3, 2]])

In [124]:
alt_b[0,0] = 9999
alt_b

array([[9999,    6],
       [   5,    6],
       [   3,    2]])

In [125]:
m # m değişmedi!

array([[6, 6, 8, 4, 7],
       [5, 6, 3, 5, 1],
       [3, 2, 0, 9, 6],
       [5, 4, 6, 0, 5],
       [8, 7, 8, 0, 8]])

# Fancy Index! ile Elemanlara Erişmek !ÖNEMLİ bir yaklaşım

In [126]:
v = np.arange(0, 30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [127]:
al_getir = [1,3,5]
v[al_getir]

array([ 3,  9, 15])

In [128]:
#iki boyutta fancy

In [129]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
satir = np.array([1,1])
sutun = np.array([1,2])
m[satir,sutun]

array([4, 5])

In [131]:
#basit index ile fancy index

In [132]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [133]:
m[0,[1,2]]

array([1, 2])

In [137]:
#slice ile fancy

In [136]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [139]:
v = np.array([1,2,3,4,5])

In [143]:
v < 3

array([ True,  True, False, False, False])

In [142]:
v[v < 3]

array([1, 2])

In [144]:
v[v != 3]

array([1, 2, 4, 5])

In [145]:
v * 2

array([ 2,  4,  6,  8, 10])

In [146]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

# Matematiksel İşlemler

In [147]:
v = np.array([1,2,3,4,5])
v-1

array([0, 1, 2, 3, 4])

In [148]:
#ufunc

In [149]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [150]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [151]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [152]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [153]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [155]:
np.power(v,3)

array([  1,   8,  27,  64, 125])

In [156]:
np.mod(v,2)

array([1, 0, 1, 0, 1])

In [157]:
np.absolute(np.array([-3]))

array([3])

In [158]:
np.sin(360)

0.9589157234143065

In [159]:
np.cos(180)

-0.5984600690578581

In [160]:
v = np.array([1,2,3])
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [161]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [162]:
?np

Type:        module
String form: <module 'numpy' from '/Users/miray/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 

In [163]:
#cheatsheet diye aratarak belli kutuphanelerin vs kısa dökümanına ulaşabiliriz.

# İki Bilinmeyenli Denklem Çözümü

5*x0 + x1 = 12
x0 + 3*x1 = 10

In [166]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

# Pandas Serisi Oluşturma

In [167]:
import pandas as pd

In [175]:
seri = pd.Series([10,45,33,4,5])
seri

0    10
1    45
2    33
3     4
4     5
dtype: int64

In [171]:
type(seri)

pandas.core.series.Series

In [172]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [176]:
seri.dtype

dtype('int64')

In [177]:
seri.size

5

In [178]:
seri.ndim

1

In [179]:
seri.values

array([10, 45, 33,  4,  5])

In [181]:
seri.head(3) #headde ilk 5 değer

0    10
1    45
2    33
dtype: int64

In [182]:
seri.tail(3)

2    33
3     4
4     5
dtype: int64

In [183]:
# index isimlendirmesi

In [184]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [188]:
pd.Series([99,22,332,94,5], index =[1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [190]:
pd.Series([99,22,332,94,5], index =["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [192]:
seri = pd.Series([99,22,332,94,5], index =["a","b","c","d","e"])
seri["a"]

99

In [193]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [195]:
#sözlük üzerinden liste oluşturmak

In [197]:
sozluk = pd.Series({"reg":10,"log":11,"cart":12})
sozluk

reg     10
log     11
cart    12
dtype: int64

In [199]:
sozluk = {"reg":10,"log":11,"cart":12}
seri = pd.Series(sozluk)
seri

reg     10
log     11
cart    12
dtype: int64

In [200]:
#iki seriyi birleştirerek seri oluşturma

In [201]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [203]:
a = np.array([1,2,33,34,45])
seri = pd.Series(a)
seri

0     1
1     2
2    33
3    34
4    45
dtype: int64

In [205]:
seri = pd.Series([121,211,130,99], index = ["reg","l","c","e"])
seri

reg    121
l      211
c      130
e       99
dtype: int64

In [206]:
seri.index

Index(['reg', 'l', 'c', 'e'], dtype='object')

In [207]:
seri.keys

<bound method Series.keys of reg    121
l      211
c      130
e       99
dtype: int64>

In [208]:
list(seri.items())

[('reg', 121), ('l', 211), ('c', 130), ('e', 99)]

In [209]:
seri.values

array([121, 211, 130,  99])

In [210]:
#eleman sorgulama

In [211]:
"reg" in seri

True

In [212]:
#fancy eleman

In [214]:
seri[["l","reg"]]

l      211
reg    121
dtype: int64

In [216]:
seri["reg"] = 130
seri["reg"]

130

In [217]:
seri["reg":"c"]

reg    130
l      211
c      130
dtype: int64

# Pandas DataFrame Oluşturma

In [219]:
l = [1,2,23,323,31]
l

[1, 2, 23, 323, 31]

In [221]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             23
3            323
4             31

In [222]:
m = np.arange(1,10).reshape((3,3))

In [223]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [224]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [225]:
#df isimlendirme

In [226]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [227]:
df.columns=("d1","d2","d3")
df

d1  d2  d3
0   1   2   3
1   4   5   6
2   7   8   9

In [228]:
type(df)

pandas.core.frame.DataFrame

In [229]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['d1', 'd2', 'd3'], dtype='object')]

In [230]:
df.shape

(3, 3)

In [231]:
df.ndim

2

In [232]:
df.size

9

In [233]:
df.values #değerleri çekip npye döner

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [234]:
df.tail(2)

d1  d2  d3
1   4   5   6
2   7   8   9

In [236]:
df

d1  d2  d3
0   1   2   3
1   4   5   6
2   7   8   9

In [237]:
a = np.array([1,2,3,4,5])
pd.DataFrame(a,columns = ["deg"])

deg
0    1
1    2
2    3
3    4
4    5

# Eleman İşlemleri

In [238]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)
sozluk = {"var1":s1,"var2":s2,"var3":s3}

In [239]:
sozluk

{'var1': array([6, 6, 3, 3, 7]),
 'var2': array([0, 6, 2, 2, 7]),
 'var3': array([7, 0, 7, 2, 9])}

In [253]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     6     0     7
1     6     6     0
2     3     2     7
3     3     2     2
4     7     7     9

In [254]:
df[0:1]

var1  var2  var3
0     6     0     7

In [244]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [255]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     6     0     7
b     6     6     0
c     3     2     7
d     3     2     2
e     7     7     9

In [246]:
df["c":"e"]

var1  var2  var3
c     3     2     7
d     3     2     2
e     7     7     9

In [247]:
#silme

In [256]:
df.drop("a",axis = 0)

var1  var2  var3
b     6     6     0
c     3     2     7
d     3     2     2
e     7     7     9

In [257]:
df # a duruyor

var1  var2  var3
a     6     0     7
b     6     6     0
c     3     2     7
d     3     2     2
e     7     7     9

In [258]:
df.drop("a",axis = 0, inplace = True) #kalıcı değişiklik için
df

var1  var2  var3
b     6     6     0
c     3     2     7
d     3     2     2
e     7     7     9

In [259]:
#fancy

In [260]:
l = ["c","e"]

In [261]:
df.drop(l, axis = 0)

var1  var2  var3
b     6     6     0
d     3     2     2

In [262]:
#değişkenler için

In [263]:
"var1" in df

True

In [264]:
l = ["var1","var4","var2"]
for i in l:
    print(i in df)

True
False
True


In [265]:
df

var1  var2  var3
b     6     6     0
c     3     2     7
d     3     2     2
e     7     7     9

In [266]:
df["var1"]

b    6
c    3
d    3
e    7
Name: var1, dtype: int64

In [268]:
df["var4"] = df["var1"] / df["var2"]
df

var1  var2  var3  var4
b     6     6     0   1.0
c     3     2     7   1.5
d     3     2     2   1.5
e     7     7     9   1.0

In [269]:
#degişken silmek

In [271]:
df.drop("var4", axis = 1)

var1  var2  var3
b     6     6     0
c     3     2     7
d     3     2     2
e     7     7     9

In [272]:
l = ["var1","var2"]
df.drop(l,axis = 1)

var3  var4
b     0   1.0
c     7   1.5
d     2   1.5
e     9   1.0

# Gözlem ve Değişken Seçimi

In [275]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    11     2    13
1    23     8    17
2    26    20    23
3    24     8    29
4    26     3    24
5     3     8    10
6    11    23     3
7    24    24    12
8    21    26     8
9    27    23    19

In [276]:
#loc: tanımlandığı şekliyle seçim yapmak için kullanılır

In [277]:
df.loc[0:3]

var1  var2  var3
0    11     2    13
1    23     8    17
2    26    20    23
3    24     8    29

In [279]:
#iloc: alışık oluduğumuz indexleme mantığıyla seçim yapar

In [280]:
df.iloc[0:3]

var1  var2  var3
0    11     2    13
1    23     8    17
2    26    20    23

In [282]:
df.iloc[0,0]

11

In [283]:
df

var1  var2  var3
0    11     2    13
1    23     8    17
2    26    20    23
3    24     8    29
4    26     3    24
5     3     8    10
6    11    23     3
7    24    24    12
8    21    26     8
9    27    23    19

In [284]:
df.iloc[:3,:2]

var1  var2
0    11     2
1    23     8
2    26    20

In [286]:
df.loc[0:3,"var3"]

0    13
1    17
2    23
3    29
Name: var3, dtype: int64

In [288]:
df.iloc[:3]["var3"]

0    13
1    17
2    23
Name: var3, dtype: int64

# Koşullu eleman işlemleri

In [289]:
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    26    17     9
1    29     1    21
2    20     5    12
3    13    10    23
4    27    14    25
5    14    18    27
6    11     9    21
7    29    16     2
8    24    15    10
9    29     4    20

In [290]:
df["var1"]

0    26
1    29
2    20
3    13
4    27
5    14
6    11
7    29
8    24
9    29
Name: var1, dtype: int64

In [291]:
df["var1"][:2]

0    26
1    29
Name: var1, dtype: int64

In [292]:
df[:2]["var1"]

0    26
1    29
Name: var1, dtype: int64

In [293]:
df[:2]["var1"]["var2"]

KeyError: 'var2'

In [297]:
df[0:2][["var1","var2"]]

var1  var2
0    26    17
1    29     1

In [299]:
df.var1

0    26
1    29
2    20
3    13
4    27
5    14
6    11
7    29
8    24
9    29
Name: var1, dtype: int64

In [303]:
df[df.var1 > 15]["var2"]

0    17
1     1
2     5
4    14
7    16
8    15
9     4
Name: var2, dtype: int64

In [304]:
df[(df.var1 > 15) & (df.var3 < 5)]

var1  var2  var3
7    29    16     2

In [306]:
df.loc[(df.var1 > 15), ["var1" , "var2"]]

var1  var2
0    26    17
1    29     1
2    20     5
4    27    14
7    29    16
8    24    15
9    29     4

In [307]:
df[(df.var1 > 15)][["var1" , "var2"]]

var1  var2
0    26    17
1    29     1
2    20     5
4    27    14
7    29    16
8    24    15
9    29     4

# Birleştirme (Join İşlemleri

In [308]:
m = np.random.randint(1,30, size = (5,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0     2    14     5
1     2    18    11
2     4     9    20
3    23    18    19
4     5    15    12

In [310]:
df2 = df + 99
df2

var1  var2  var3
0   101   113   104
1   101   117   110
2   103   108   119
3   122   117   118
4   104   114   111

In [312]:
pd.concat([df,df2]) #ikisi de 4e gidiyor

var1  var2  var3
0     2    14     5
1     2    18    11
2     4     9    20
3    23    18    19
4     5    15    12
0   101   113   104
1   101   117   110
2   103   108   119
3   122   117   118
4   104   114   111

In [313]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[Hashable, NDFrame]',
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, defa

In [315]:
pd.concat([df,df2], ignore_index = True) #endekse göre numaralandırma yapıp çözdük

var1  var2  var3
0     2    14     5
1     2    18    11
2     4     9    20
3    23    18    19
4     5    15    12
5   101   113   104
6   101   117   110
7   103   108   119
8   122   117   118
9   104   114   111

In [316]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [317]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [319]:
df2.columns = ["var1","var2","deg3"]
df2

var1  var2  deg3
0   101   113   104
1   101   117   110
2   103   108   119
3   122   117   118
4   104   114   111

In [320]:
df

var1  var2  var3
0     2    14     5
1     2    18    11
2     4     9    20
3    23    18    19
4     5    15    12

In [321]:
pd.concat([df,df2])

var1  var2  var3   deg3
0     2    14   5.0    NaN
1     2    18  11.0    NaN
2     4     9  20.0    NaN
3    23    18  19.0    NaN
4     5    15  12.0    NaN
0   101   113   NaN  104.0
1   101   117   NaN  110.0
2   103   108   NaN  119.0
3   122   117   NaN  118.0
4   104   114   NaN  111.0

In [322]:
pd.concat([df,df2], join = "inner") #ortak değişkenlerini birleştiriyor!

var1  var2
0     2    14
1     2    18
2     4     9
3    23    18
4     5    15
0   101   113
1   101   117
2   103   108
3   122   117
4   104   114

# İleri Birleştirme İşlemleri

In [331]:
#birebir birleştirme

In [332]:
df1 = pd.DataFrame({"calisanlar": ["ali","veli","ayse","fatma"],"grup":["muhasebe","muhendislik","muhendislik","ik"]})
df1

calisanlar         grup
0        ali     muhasebe
1       veli  muhendislik
2       ayse  muhendislik
3      fatma           ik

In [334]:
df2 = pd.DataFrame({"calisanlar": ["ali","veli","ayse","fatma"],"ilk_giris":[2010,2009,2014,2019]})
df2

calisanlar  ilk_giris
0        ali       2010
1       veli       2009
2       ayse       2014
3      fatma       2019

In [335]:
df1 = pd.DataFrame({"calisanlar": ["ali","veli","ayse","fatma"],"grup":["muhasebe","muhendislik","muhendislik","ik"]})
pd.merge(df1,df2)

calisanlar         grup  ilk_giris
0        ali     muhasebe       2010
1       veli  muhendislik       2009
2       ayse  muhendislik       2014
3      fatma           ik       2019

In [336]:
#coktan teke

In [339]:
df3 = pd.merge(df1,df2)
df3

calisanlar         grup  ilk_giris
0        ali     muhasebe       2010
1       veli  muhendislik       2009
2       ayse  muhendislik       2014
3      fatma           ik       2019

In [341]:
df4 = pd.DataFrame({"grup": ["muhasebe","muhendislik","ik"],"mudur":["caner","mustafa","berkcan"]})
df4

grup    mudur
0     muhasebe    caner
1  muhendislik  mustafa
2           ik  berkcan

In [342]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        ali     muhasebe       2010    caner
1       veli  muhendislik       2009  mustafa
2       ayse  muhendislik       2014  mustafa
3      fatma           ik       2019  berkcan

In [343]:
#coktan coka

In [345]:
df5 = pd.DataFrame({"grup":["muhasebe","muhasebe","muhendislik","muhendislik","ik","ik"],
                    "yetenekler": ["matematik","excel","kodlama","linux","excel","yonetim"],})
df5

grup yetenekler
0     muhasebe  matematik
1     muhasebe      excel
2  muhendislik    kodlama
3  muhendislik      linux
4           ik      excel
5           ik    yonetim

In [346]:
df1

calisanlar         grup
0        ali     muhasebe
1       veli  muhendislik
2       ayse  muhendislik
3      fatma           ik

In [347]:
pd.merge(df1,df5)

calisanlar         grup yetenekler
0        ali     muhasebe  matematik
1        ali     muhasebe      excel
2       veli  muhendislik    kodlama
3       veli  muhendislik      linux
4       ayse  muhendislik    kodlama
5       ayse  muhendislik      linux
6      fatma           ik      excel
7      fatma           ik    yonetim

# Toplulaştırma ve Gruplama! (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:
* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()
* decribe()!

In [348]:
import seaborn as sns

In [352]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [351]:
?sns.load_dataset

Signature: sns.load_dataset(name, cache=True, data_home=None, **kws)
Docstring:
Load an example dataset from the online repository (requires internet).

This function provides quick access to a small number of example datasets
that are useful for documenting seaborn or generating reproducible examples
for bug reports. It is not necessary for normal usage.

Note that some of the datasets have a small amount of preprocessing applied
to define a proper ordering for categorical variables.

Use :func:`get_dataset_names` to see a list of available datasets.

Parameters
----------
name : str
    Name of the dataset (``{name}.csv`` on
    https://github.com/mwaskom/seaborn-data).
cache : boolean, optional
    If True, try to load from the local cache first, and save to the cache
    if a download is required.
data_home : string, optional
    The directory in which to cache data; see :func:`get_data_home`.
kws : keys and values, optional
    Additional keyword arguments are passed to passed thr

In [353]:
df.shape

(1035, 6)

In [357]:
df["mass"].mean()

2.6381605847953233

In [358]:
df["mass"].count()

513

In [359]:
df["mass"].min()

0.0036

In [360]:
df["mass"].max()

25.0

In [361]:
df["mass"].sum()

1353.37638

In [362]:
df["mass"].std()

3.8186166509616046

In [363]:
df["mass"].var()

14.58183312700122

In [365]:
df.describe().T #temel betimsel ve dağılım istatistikleri (.T transpose)

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [366]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri

In [369]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                    "veri": [10,11,52,23,43,55]},columns=["gruplar","veri"])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [370]:
df.groupby("gruplar")

In [371]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [372]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [373]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [374]:
df.groupby("method")

In [377]:
df.groupby("method")["orbital_period"].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [378]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                    "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [379]:
#aggregate

In [380]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [382]:
df.groupby("gruplar").aggregate([min,np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [383]:
df.groupby("gruplar").aggregate([min,np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [384]:
df.groupby("gruplar").aggregate({"degisken1": min, "degisken2": max})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [385]:
# filter

In [386]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                    "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [387]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [388]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [389]:
#transform

In [390]:
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [395]:
df_a = df.iloc[:,1:3]
df_a

degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [397]:
df_a.transform(lambda x: x-x.mean())

degisken1  degisken2
0      -23.0     -238.0
1      -10.0      -85.0
2        0.0       -5.0
3      -11.0      -76.0
4      -22.0     -227.0
5       66.0      631.0

In [398]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [399]:
#apply

In [403]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                    "degisken1": [10,23,33,22,11,99],
                  "degisken2": [100,253,333,262,111,969]},columns=["gruplar","degisken1","degisken2"])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [402]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [408]:
df.groupby("gruplar").apply(np.sum)

gruplar  degisken1  degisken2
gruplar                              
A            AA         32        362
B            BB         34        364
C            CC        132       1302

# Pivot Tablolar

In [413]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [414]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [415]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [418]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [419]:
#pivot ile pivot table

In [421]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [422]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [426]:
age = pd.cut(titanic["age"],[0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [428]:
titanic.pivot_table("survived", ["sex",age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okumak

In [431]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [432]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [433]:
pd.read_excel("reading_data/ornekx.xlsx")  

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [435]:
df = pd.read_excel("reading_data/ornekx.xlsx")  

In [436]:
type(df)

pandas.core.frame.DataFrame

In [438]:
df.columns = ("A","B","C")
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0